pref("extensions.scrapbook.addon.autosave.enabled", true);
pref("extensions.scrapbook.addon.autosave.images", true);
pref("extensions.scrapbook.addon.autosave.media", true);
pref("extensions.scrapbook.addon.autosave.fonts", true);
pref("extensions.scrapbook.addon.autosave.styles", true);
pref("extensions.scrapbook.addon.autosave.script", false);
pref("extensions.scrapbook.addon.autosave.ignore", false);
pref("extensions.scrapbook.addon.autosave.include", "");
pref("extensions.scrapbook.addon.autosave.exclude", "");
